name: Messing with kafka

on:
  push:
    branches:
      - 'SMAT-173_mess-with-kafka'

jobs:
  test-kafka:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup test environment
        run: |
          cd test/soveren-middleware-chaos
          docker-compose up -d

          # wait until env is up
          sleep 3
          t=0
          while (( t <= 30 )); do
            (( t+=1 ))
            curl localhost:8090/get | grep 'OK: backend'
            [[ $? -eq 0 ]] && break || sleep 1
          done
          curl -v localhost:8090/get-json; echo

      - name: Run some ab instances
        run: |
          cd test/soveren-middleware-chaos
          ab -c 1 -t 600 -s 1 http://localhost:8090/get      &> ab1.log &
          echo $! > ab1.pid
          ab -c 1 -t 600 -s 1 http://localhost:8090/get-json &> ab2.log &
          echo $! > ab2.pid
          curl -v localhost:8090/get-json; echo

      - name: Mess with kafka
        run: |
          curl -v localhost:8090/get-json; echo
          cd test/soveren-middleware-chaos
          docker-compose restart kafka
          sleep 10
          docker-compose kill kafka
          sleep 3
          docker-compose start kafka
          sleep 10
          curl -v localhost:8090/get-json; echo

          # check if ab still running
          if kill -0 $(cat ab1.pid ab2.pid); then
            echo "ab still working"
          else
            cat ab1.log
            cat ab2.log
            docker-compose logs proxy
            docker-compose logs backend
            exit 1
          fi

      - name: Stop ab and show its logs
        run: |
          curl -v localhost:8090/get-json; echo
          cd test/soveren-middleware-chaos
          # stop ab
          kill -2 $(cat ab1.pid ab2.pid)
          sleep 1

          # show logs
          cat ab1.log
          cat ab2.log
          curl -v localhost:8090/get-json; echo

      - name: Show kafka logs
        run: |
          cd test/soveren-middleware-chaos
          docker-compose logs kafka

      - name: Show backend logs
        run: |
          cd test/soveren-middleware-chaos
          docker-compose logs backend

      - name: Show proxy logs
        run: |
          cd test/soveren-middleware-chaos
          docker-compose logs proxy
