name: Messing with kafka

on:
  push:
    branches:
      - 'SMAT-173_mess-with-kafka'

jobs:
  test-kafka:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup test environment
        run: |
          cd test/soveren-middleware-chaos
          docker-compose up -d

      - name: Run some ab instances
        run: |
          ab -c 1 -t 600 -s 1 http://localhost:8090/get      > ab1.log &
          echo $! > ab1.pid
          ab -c 1 -t 600 -s 1 http://localhost:8090/get-json > ab2.log &
          echo $! > ab2.pid

      - name: Mess with zookeeper
        run: |
          docker-compose restart zookeeper
          sleep 10
          docker-compose kill zookeeper
          sleep 10
          docker-compose start zookeeper
          sleep 10

          # check if ab still running
          kill -0 $(cat ab1.pid) || exit 1
          kill -0 $(cat ab2.pid) || exit 1

      - name: Mess with kafka
        run: |
          docker-compose restart kafka
          sleep 10
          docker-compose kill kafka
          sleep 10
          docker-compose start kafka
          sleep 10

          # check if ab still running
          kill -0 $(cat ab1.pid) || exit 1
          kill -0 $(cat ab2.pid) || exit 1

      - name: Stop ab and show its logs
        run: |
          # stop ab
          kill -2 $(cat ab1.pid)
          kill -2 $(cat ab2.pid)
          sleep 1

          # show logs
          cat ab1.log
          cat ab2.log
